"""max and mnin

Revision ID: a182fd0a9058
Revises: f890becda8c7
Create Date: 2021-02-25 12:55:58.203331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a182fd0a9058'
down_revision = 'f890becda8c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('max_price', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('min_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'min_price')
    op.drop_column('product', 'max_price')
    # ### end Alembic commands ###
